##configure redirects in this file
[[redirects]]
  from = "https://smiledesign-nj.com*"
  to = "https://smiledesign-nj.netlify.app"
  status = 301
  force = true

[[redirects]]
  from = "https://smiledesign-nj.com"
  to = "https://smiledesign-nj.netlify.app"
  status = 301
  force = true

[[redirects]]
  from = "https://www.smiledesign-nj.com"
  to = "https://smiledesign-nj.netlify.app"
  status = 301
  force = true

[[redirects]]
  from = "https://www.smiledesign-nj.netlify.app"
  to = "https://smiledesign-nj.netlify.app"
  status = 301
  force = true